# -*- coding: utf-8 -*-
"""Satyam_Theurkar_TASK_2. Predictive Analysis Using Machine Learning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqEix93TPkyVCfGo9GCh-xaQ8lmNjxmV
"""

import pandas as pd

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/drive/MyDrive/task data set/students.csv")

# Predictive analysis for Average GPA

df = df.drop(columns=["Student ID", "Name", "Internship Domain", "Placement Domain", "Placement Status", "Alumni Path", "Skills"])

df = df.dropna(subset=["Average GPA"])
df = df.dropna()

label_cols = ["Gender", "Branch", "Clubs", "Internship Done"]
for col in label_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

X = df.drop("Average GPA", axis=1)
y = df["Average GPA"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")